# Eureka server configurations
server:
  port: 8761
spring:
  application:
    name: discovery-server

eureka:
  instance:
    preferIpAddress: true
  client:
    # Prevents register itself
    fetch-registry: false
    register-with-eureka: false
